# Generated by Django 6.0.1 on 2026-02-23 05:36

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    categories = [
        "Arts",
        "Charity",
        "Community",
        "Corporate",
        "Educational & Workshops",
        "Entertainment",
        "Family & Kids",
        "Food",
        "Private",
        "Seasonal",
        "Sports & Outdoors",
        "Tech & Innovation",
        "Weddings & Romance",
        "Other",
    ]
    for name in categories:
        Category.objects.get_or_create(name=name)


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),  # adjust if your migration number differs
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
